//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renat_A_Ride.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class normalService
    {
        public int serviceID { get; set; }
        public Nullable<int> userservID { get; set; }
        public Nullable<int> carID { get; set; }
        public string pickupAddress { get; set; }
        public string dropAddress { get; set; }
        public System.DateTime dateAndTime { get; set; }
    
        public virtual car car { get; set; }
        public virtual User User { get; set; }
    }
}
