//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renat_A_Ride.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weeklyService
    {
        public int weekID { get; set; }
        public string rate { get; set; }
    }
}
